SELECT PCOFERTAPROGRAMADAI.CODOFERTA, 
       PCOFERTAPROGRAMADAI.CODFILIAL, 
       PCOFERTAPROGRAMADAI.CODAUXILIAR, 
       PCOFERTAPROGRAMADAI.VLOFERTA, 
       PCOFERTAPROGRAMADAI.VLOFERTAATAC, 
       PCOFERTAPROGRAMADAI.MOTIVOOFERTA, 
       PCOFERTAPROGRAMADAI.QTMAXVENDA, 
       PCOFERTAPROGRAMADAI.DATAEXCLUSAO,
       PCOFERTAPROGRAMADAC.DESCOFERTA
  FROM PCOFERTAPROGRAMADAI
 INNER JOIN PCOFERTAPROGRAMADAC on PCOFERTAPROGRAMADAC.CODOFERTA = PCOFERTAPROGRAMADAI.CODOFERTA 
 WHERE PCOFERTAPROGRAMADAI.CODAUXILIAR = :CODAUXILIAR  
 AND PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NULL
 AND (TRUNC(SYSDATE) BETWEEN PCOFERTAPROGRAMADAC.DTINICIAL AND PCOFERTAPROGRAMADAC.DTFINAL) AND (PCOFERTAPROGRAMADAC.DTCANCEL IS NULL)
 FETCH FIRST 1 ROWS ONLY;