SELECT
    CAST(0 AS INTEGER) COR_LEGENDA,
    PCEMBALAGEM.CODFILIAL,
    PCOFERTAPROGRAMADAI.CODOFERTA,
    PCOFERTAPROGRAMADAI.CODITEM,
    PCEMBALAGEM.CODAUXILIAR,
    PCEMBALAGEM.UNIDADE,
CASE
        WHEN :DESCRICAOPRODUTO = 'S' THEN PCPRODUT.DESCRICAO
        ELSE NVL(PCEMBALAGEM.DESCRICAOECF, PCPRODUT.DESCRICAO)
    END DESCRICAO,
    NVL(PCOFERTAPROGRAMADAI.CODPROD, PCEMBALAGEM.CODPROD) CODPROD,
    PCOFERTAPROGRAMADAI.VLOFERTA,
    PCOFERTAPROGRAMADAI.MOTIVOOFERTA,
    PCOFERTAPROGRAMADAI.QTMAXVENDA,
    PCOFERTAPROGRAMADAI.QTMAXOFERTA,
    PCOFERTAPROGRAMADAI.VLOFERTAATAC,
    PCOFERTAPROGRAMADAI.VLOFERTA VLOFERTA_OLD,
    PCOFERTAPROGRAMADAI.VLOFERTAATAC VLOFERTAATAC_OLD,
    'N' PRECOOFERTAALTERADO,
    'N' PRECOOFERTAATACALTERADO,
    PCOFERTAPROGRAMADAI.DATAEXCLUSAO,
CASE
        WHEN PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NOT NULL THEN 'Sim'
        ELSE 'Não'
    END PRODUTOEXCLUIDO,
    NVL(PCOFERTAPROGRAMADAI.RECOMPOSICAO, 'N') RECOMPOSICAO,
    NVL(PCEMBALAGEM.QTMINIMAATACADO, 0) QTMINIMAATACADO,
    NVL(PCEMBALAGEM.QTMULTIPLA, 0) QTMULTIPLA,
    PCOFERTAPROGRAMADAI.MOTIVO,
    PCPRODUT.CODPRODPRINC,
    PCPRODUT.DESCRICAO AS DESCRICAOPRODUTO,
    PCEMBALAGEM.QTUNIT,
    PCEMBALAGEM.EMBALAGEM,
CASE
        PARAMFILIAL.OBTERCOMONUMBER('CON_SUGVENDA')
        WHEN 1 THEN PCEST.CUSTOREAL
        WHEN 2 THEN PCEST.CUSTOFIN
        WHEN 3 THEN PCEST.CUSTOULTENT
        WHEN 4 THEN PCEST.CUSTOULTPEDCOMPRA
        WHEN 5 THEN PCEST.CUSTOULTENTFIN
        WHEN 6 THEN PCEST.CUSTOPROXIMACOMPRA
        WHEN 7 THEN PCEST.CUSTOFORNEC
        ELSE PCEST.CUSTOULTENT
    END CUSTO,
    DECODE(
        NVL(PCEMBALAGEM.FATORPRECO, 1),
        0,
        1,
        NVL(PCEMBALAGEM.FATORPRECO, 1)
    ) FATORPRECO,
    'S' EMBALAGEMVALIDA,
    DECODE(
        FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('UTILIZAMARGEMSUBCAT', '1', 'N'),
        'N',
        PCPRODUT.MARGEMMIN,
        (
            SELECT
                PCCLASSIFICMERC.MARGEMMINVAREJO
            FROM
                PCCLASSIFICMERC
            WHERE
                PCCLASSIFICMERC.CODFILIAL = :CODFILIAL
                AND PCCLASSIFICMERC.CODPROD = PCPRODUT.CODPROD
                AND PCCLASSIFICMERC.CODDEPTO = PCPRODUT.CODEPTO
                AND PCCLASSIFICMERC.CODSEC = PCPRODUT.CODSEC
                AND PCCLASSIFICMERC.CODCATEGORIA = PCPRODUT.CODCATEGORIA
                AND PCCLASSIFICMERC.CODSUBCATEGORIA = PCPRODUT.CODSUBCATEGORIA
        )
    ) MARGEMMIN,
    DECODE(
        FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('UTILIZAMARGEMSUBCAT', '1', 'N'),
        'N',
        PCEMBALAGEM.MARGEM,
        (
            SELECT
                PCCLASSIFICMERC.MARGEMVAREJO
            FROM
                PCCLASSIFICMERC
            WHERE
                PCCLASSIFICMERC.CODFILIAL = :CODFILIAL
                AND PCCLASSIFICMERC.CODPROD = PCPRODUT.CODPROD
                AND PCCLASSIFICMERC.CODDEPTO = PCPRODUT.CODEPTO
                AND PCCLASSIFICMERC.CODSEC = PCPRODUT.CODSEC
                AND PCCLASSIFICMERC.CODCATEGORIA = PCPRODUT.CODCATEGORIA
                AND PCCLASSIFICMERC.CODSUBCATEGORIA = PCPRODUT.CODSUBCATEGORIA
        )
    ) MARGEMIDEAL
FROM
    PCEST,
    PCPRODUT,
    PCOFERTAPROGRAMADAI,
    PCEMBALAGEM
WHERE
    PCOFERTAPROGRAMADAI.CODOFERTA = :CODOFERTA
    AND PCOFERTAPROGRAMADAI.CODFILIAL = :CODFILIAL
    AND PCEST.CODPROD = PCEMBALAGEM.CODPROD
    AND PCEST.CODFILIAL = PCEMBALAGEM.CODFILIAL
    AND PCOFERTAPROGRAMADAI.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR
    AND PCOFERTAPROGRAMADAI.CODFILIAL = PCEMBALAGEM.CODFILIAL
    AND PCEMBALAGEM.CODPROD = PCPRODUT.CODPROD