 SELECT TO_CHAR(HORAINICIAL, 'HH24:MI:SS') HORAINICIAL 
       ,TO_CHAR(HORAFINAL,'HH24:MI:SS') HORAFINAL     
       ,PCOFERTAPROGRAMADAC.* FROM PCOFERTAPROGRAMADAC  
 WHERE 1=1                                              
AND (TRUNC(SYSDATE) BETWEEN PCOFERTAPROGRAMADAC.DTINICIAL AND PCOFERTAPROGRAMADAC.DTFINAL) AND (PCOFERTAPROGRAMADAC.DTCANCEL IS NULL)
ORDER BY PCOFERTAPROGRAMADAC.CODOFERTA